version: 1.1.{build}
image: Linux
build_cloud: UBUNTU-PROD-DO
before_build:
- systemctl stop beserver
- nuget restore
nuget:
  project_feed: true
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: normal
  project: BEServer.Nanick.sln
after_build:
- systemctl start beserver
